### ISSUE TITLE
Spelling Error on README.md at root.

### ISSUE THREAD

**Issue by ForrestErickson** [nk25719/ONOFFLAMP#1]
# Summary
Spelling error on first line.

## Corrective action
Change from: I am practicing designing PCBs, with Mr. Forest Lee Erickson mentoring me.
To: I am practicing designing PCBs, with Mr. Forrest Lee Erickson mentoring me.

**Comment by ForrestErickson** [comment]
@nk25719 

Nagham, 
After you make the correction you will make a comment describing your fix and then press the "Close with comment" button below.

**Comment by ForrestErickson** [comment]
If you type the "@" sign and then start typing my name it may auto fill and tag me with a message.  Try it. @ForrestErickson 

See:
![image](https://github.com/nk25719/ONOFFLAMP/assets/5836181/7d74c662-f69a-4376-b59f-b972d4813134)

I some times use this style.

CC: @nk25719

**Comment by nk25719** [comment]
CC: @ForrestErickson  

I made the necessary changes. Let me know if you spot another error.
## Thank you @ForrestErickson.
